### ISSUE TITLE
Execution failed for task ':react-native-freshchat-sdk:verifyReleaseResources'

### ISSUE THREAD

**Issue by hamzaehsan95** [adrianha/react-native-freshchat-sdk#16]
Generating android release APK leads to the following exception.

Execution failed for task ':react-native-freshchat-sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/hamza/.gradle/caches/transforms-3/0a4c265a7f3592dd47160af79522aea3/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

BuildTools version: "30.0.2"
target Sdk = 31
compile Sdk  = 31

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40752813/200531768-5a2cff5b-b078-4642-abb4-6e2043877c7d.png">

**Comment by MShokry** [comment]
@hamzaehsan95 
Any update? 
Did you find any solution?

**Comment by hamzaehsan95** [comment]
Just to sort out, I manually updated this particular package build.gradle file in node modules. I updated the compile and target sdk versions and the build number to these below and it worked.

BuildTools version: "30.0.2"
target Sdk = 31
compile Sdk = 31

**Comment by MShokry** [comment]
@hamzaehsan95  Thanks for support

for me

1- I updated node_modules/react-native-freshchat-sdk/android/build.gradle with
`android {
    compileSdkVersion = 31
    buildToolsVersion = "31.0.0"
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"
    }
}`

2- using package patch to apply the patch across the team and each time needed
`npx patch-package react-native-freshchat-sdk`

3- adding the following to android/build.gradle
`configurations.all {
        resolutionStrategy.force 'androidx.appcompat:appcompat:1.3.0'
    }
`
 
I hope it helps others
