### ISSUE TITLE
Can not compile on Android

### ISSUE THREAD

**Issue by RichardLindhout** [adrianha/react-native-freshchat-sdk#2]
* What went wrong:
Execution failed for task ':react-native-freshchat-sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/richardlindhout/.gradle/caches/transforms-2/files-2.1/26a73ccff5a93baf5a1326f3b8191a92/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     /Users/richardlindhout/.gradle/caches/transforms-2/files-2.1/26a73ccff5a93baf5a1326f3b8191a92/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

     /Users/richardlindhout/.gradle/caches/transforms-2/files-2.1/0a32ebb7e31fc441cb7f8f0d18d1bec5/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/richardlindhout/.gradle/caches/transforms-2/files-2.1/0a32ebb7e31fc441cb7f8f0d18d1bec5/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by RichardLindhout** [comment]
Fixed it by updating the buildtoolsversio etc in the Gradle file of this library

**Comment by tkyr-hh** [comment]
@RichardLindhout  what is the build tools version you've used or did you upgrade it to the latest version ??
